name = "yae-wiki"
main = "src/index.ts"
compatibility_date = "2023-08-05"

# id (for production) is a required field, but you can set it to the same as
# preview_id until you need to separate them
kv_namespaces = [
  { binding = "PAGES", id = "xxx", preview_id = "xxx" },
  { binding = "PAGE_INDEX", id = "xxx", preview_id = "xxx" },
  { binding = "USERS", id = "xxx", preview_id ="xxx"},
  { binding = "USERS_INDEX",id = "xxx",preview_id = "xxx"},
  { binding = "PAGE_HISTORY", id = "xxx", preview_id = "xxx" }
]
#you should replace the above ids with your own
